name = "web-native-monorepo-template-api"
main = "src/index.ts"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding (開発環境用)
[[d1_databases]]
binding = "DB"
database_name = "web-native-db-dev"
database_id = "18a0c581-b5bd-4076-9848-e11f29a8abf3"
preview_database_id = "18a0c581-b5bd-4076-9848-e11f29a8abf3"
migrations_dir = "drizzle/migrations"

# ローカル開発用の環境変数
[vars]
CORS_ORIGINS = "http://localhost:3000,http://localhost:8081,http://localhost:19006"
NODE_ENV = "development"
# DATABASE_URLは.dev.varsまたはwrangler secretで設定

[env.development]
name = "web-native-monorepo-template-api-dev"
[env.development.vars]
CORS_ORIGINS = "http://localhost:3000,http://localhost:8081,http://localhost:19006"
NODE_ENV = "development"

[env.production]
name = "web-native-monorepo-template-api-prod"
[env.production.vars]
CORS_ORIGINS = "https://yourapp.com,https://www.yourapp.com"
NODE_ENV = "production"
# 本番環境の秘密情報は wrangler.local.toml または Cloudflare Dashboard で設定